DROP TABLE socialNetwork CASCADE CONSTRAINTS;
DROP TABLE user CASCADE CONSTRAINTS;
DROP TABLE friendOf CASCADE CONSTRAINTS;
DROP TABLE profile CASCADE CONSTRAINTS;
DROP TABLE worker CASCADE CONSTRAINTS;
DROP TABLE developer CASCADE CONSTRAINTS;
DROP TABLE manager CASCADE CONSTRAINTS;